### ISSUE TITLE
help its skidded

### ISSUE THREAD

**Issue by iSkidOffDanghui** [azulx/Script-Ware#1]

**Comment by Environment666** [comment]
ok so step 1 to fix this - go wherever you saved scriptware, step 2- right click, step 3 - delete, then throw your computer out in a pit of fire to make sure its gone
enjoy this method please send money at my bitcoin address: 696969696969696969

**Comment by azulx** [comment]
>help its skidded
>doesnt show anything that could invoke its skidded
go back to eternals lap
