### ISSUE TITLE
hi preview my new exploti named loki v2 

### ISSUE THREAD

**Issue by iSkidOffDanghui** [azulx/Script-Ware#2]
it works i udated script ware here link : https://www.youtube.com/watch?v=MC8CZZfZJ8s

**Comment by Melanie0001** [comment]
Does I put all the code in the execution button?

**Comment by frayray909090** [comment]
> it works i udated script ware here link : https://www.youtube.com/watch?v=MC8CZZfZJ8s

how did you compile it?
