### ISSUE TITLE
Give .exe file

### ISSUE THREAD

**Issue by Qardruss** [azulx/Script-Ware#7]
Give the .exe file

**Comment by anautonell** [comment]
Just go to script-ware.com and purchase it, it’s really cool!

**Comment by anautonell** [comment]
I had Calamrie and migrate it to script-ware for free.

**Comment by b0yk3x** [comment]
compile the source code

**Comment by shidemuri** [comment]
its been 4 year since last commit, it 100% does not work

**Comment by Qardruss** [comment]
This is old, plus I don't have the money to buy V2

**Comment by Qardruss** [comment]
And I can probably change it up and make it work, now that I'm a better developer

**Comment by Snobbish-slob** [comment]
> And I can probably change it up and make it work, now that I'm a better developer

Looks like our goals are the same, its being 4months since you commented this so are you done yet?

**Comment by Qardruss** [comment]
No, never started

**Comment by Snobbish-slob** [comment]
> No, never started

do you still aim to fix the code?

**Comment by Snobbish-slob** [comment]
> No, never started

maybe I can help ya

**Comment by Qardruss** [comment]
Okay, just I'd rather move this out of this issue then, contact me somehow I guess. I have Discord.

**Comment by frayray909090** [comment]
> compile the source code

How do I compile the code I need help

**Comment by frayray909090** [comment]
> compile the source code

How do I compile the source code

**Comment by frayray909090** [comment]
> 

How do I compile it I made it work for the newest version of rblx and it auto updates taking the code it needs from roblox updates because I’m lazy to update things

**Comment by frayray909090** [comment]
> Just go to script-ware.com and purchase it, it’s really cool!

How do I compile?
